[SERVICE]
    Flush        5
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name         tail
    Path         /var/log/consumer/*.log
    Tag          consumer.log
    Parser       json
    Refresh_Interval 5

[OUTPUT]
    Name              es
    Match             *
    Host              elasticsearch
    Port              9200
    Index             consumer-logs
    Suppress_Type_Name On
    tls               Off